title: PhD Paper Requirement Completion
#logo: /assets/img/logo.png
description: Northeastern University's PhD research paper requirement completion web-page.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_name: Aviral Goel
  owner_url: https://github.com/aviralg
